includes:
  - base.yaml
model:
  model_name: ERM
  tau: 0.2  # 
  use_bn: True
  last_activation: True
  cmi_coefficient: 0.2  
  prototypes_lr: 1e-6  
  num_clusters: 100 
  dropout_rate: 0  
ood:
  ood_alg: ERM
  ood_param: -1.
# train:
#   max_epoch: 100
#   lr: 1e-3
#   mile_stones: [150]
#   eval_step: 10

train:
  max_epoch: 100  
  lr: 1e-3  
  mile_stones: [30, 50] 

  linear_head_epochs: 100 
  linear_head_lr: 1e-3  
  eval_step: 10
aug:
  mask_feat1: 0.3
  mask_feat2: 0.3
  mask_edge1: 0.6
  mask_edge2: 0.6