includes:
  - base.yaml
model:
  model_name: EERM
  tau: 0.2
  use_bn: True
  last_activation: True
  cmi_coefficient: 0.8
  prototypes_lr: 1e-5
  num_clusters: 150
  dropout_rate: 0 
ood:
  ood_alg: EERM
  ood_param: 3.
  extra_param:
    - 10   # K: Number of context generator
    - 1   # T
    - 1   # Number of sample
    - 1e-3    # Learning rate for REINFORCE
# train:
#   max_epoch: 100
#   lr: 5e-3
#   mile_stones: [150]

train:
  max_epoch: 100
  lr: 1e-3
  mile_stones: [150]

  linear_head_epochs: 100
  linear_head_lr: 1e-3
  eval_step: 10
aug:
  mask_feat1: 0.2
  mask_feat2: 0.2
  mask_edge1: 0.6
  mask_edge2: 0.6